let state, content, dirty=false, busy=false;
const status=document.querySelector('#status');
const actions=['save','preview','publish','reset'].map(id=>document.getElementById(id));
function message(text){status.textContent=text;}
function lock(value){busy=value;actions.forEach(b=>b.disabled=value);document.querySelectorAll('#fields textarea,#units button,#units input').forEach(e=>e.disabled=value);if(!value&&content)drawPhotos();}
function changed(){dirty=true;message('Unsaved changes — save your draft when ready.');}
async function api(path,body){const response=await fetch('/api/editor/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to complete that action.');return data;}
function stamp(){document.querySelector('#published').textContent=state.publishedAt?'Last published '+new Date(state.publishedAt).toLocaleString():'Current website content';}
function drawText(){const root=document.querySelector('#fields');root.replaceChildren();const groups=new Map();for(const field of state.fields){if(!groups.has(field.group)){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=field.group;details.append(summary);root.append(details);groups.set(field.group,details);}const label=document.createElement('label');label.className='field';label.textContent=field.label;const input=document.createElement('textarea');input.value=content.text[field.key];input.maxLength=3000;input.required=true;input.addEventListener('input',()=>{content.text[field.key]=input.value;changed();});label.append(input);groups.get(field.group).append(label);}}
function drawPhotos(){const root=document.querySelector('#units');root.replaceChildren();for(const [unit,photos] of Object.entries(content.photos)){const block=document.createElement('article');block.className='unit';const head=document.createElement('div');head.className='unit-head';const title=document.createElement('h3');title.textContent=unit[0].toUpperCase()+unit.slice(1)+' · '+photos.length+' photos';const upload=document.createElement('label');upload.className='upload';upload.textContent='Add photos';const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.multiple=true;input.addEventListener('change',()=>uploadPhotos(unit,input.files));upload.append(input);head.append(title,upload);block.append(head);const grid=document.createElement('div');grid.className='photo-grid';photos.forEach((photo,index)=>{const card=document.createElement('div');card.className='photo';const img=document.createElement('img');img.src=photo.src;img.alt=photo.alt;img.loading='lazy';const number=document.createElement('span');number.className='number';number.textContent=index===0?'1 · Cover photo':String(index+1);const buttons=document.createElement('div');buttons.className='controls';for(const [label,delta] of [['←',-1],['→',1]]){const button=document.createElement('button');button.textContent=label;button.setAttribute('aria-label',`Move ${unit} photo ${index+1} ${delta<0?'earlier':'later'}`);button.disabled=index+delta<0||index+delta>=photos.length;button.onclick=()=>{[photos[index],photos[index+delta]]=[photos[index+delta],photos[index]];changed();drawPhotos();};buttons.append(button);}const remove=document.createElement('button');remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${unit} photo ${index+1}`);remove.disabled=photos.length===1;remove.onclick=()=>{photos.splice(index,1);changed();drawPhotos();};buttons.append(remove);card.append(img,number,buttons);grid.append(card);});block.append(grid);root.append(block);}}
async function compress(file){if(file.size>20000000)throw new Error('Choose photos smaller than 20 MB.');const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.8));if(!blob)throw new Error('This photo could not be processed. Try a JPEG or PNG.');return blob;}
async function uploadPhotos(unit,files){if(!files.length)return;if(content.photos[unit].length+files.length>100){message('Each unit can have up to 100 photos.');return;}lock(true);try{for(const [i,file] of [...files].entries()){message(`Preparing photo ${i+1} of ${files.length}…`);const blob=await compress(file);const response=await fetch('/api/editor/upload',{method:'POST',headers:{'Content-Type':blob.type},body:blob});const result=await response.json();if(!response.ok)throw new Error(result.error);content.photos[unit].push({src:result.src,alt:unit[0].toUpperCase()+unit.slice(1)+' accommodation photo'});dirty=true;}message('Photos added. Save your draft to keep these changes.');}catch(error){message(error.message);}finally{lock(false);drawPhotos();}}
async function save(){const saved=await api('draft',{revision:state.revision,content});state={...state,...saved};dirty=false;stamp();return saved;}
function confirmAction(title,text){const dialog=document.querySelector('#confirm');document.querySelector('#confirm-title').textContent=title;document.querySelector('#confirm-text').textContent=text;return new Promise(resolve=>{dialog.addEventListener('close',()=>resolve(dialog.returnValue==='yes'),{once:true});dialog.showModal();});}
document.querySelector('#save').onclick=async()=>{lock(true);try{await save();message('Draft saved. Your website has not changed yet.');}catch(error){message(error.message);}finally{lock(false);}};
document.querySelector('#preview').onclick=async()=>{const preview=window.open('about:blank','seajax-draft-preview');if(preview)preview.opener=null;lock(true);try{if(dirty)await save();if(preview)preview.location='/admin/preview';else message('Preview window blocked. Allow pop-ups, then try again.');if(preview)message('Saved draft preview opened in a new tab.');}catch(error){preview?.close();message(error.message);}finally{lock(false);}};
document.querySelector('#publish').onclick=async()=>{if(!await confirmAction('Publish your changes?','Your saved draft will replace the content visitors see on the website.'))return;lock(true);try{if(dirty)await save();const result=await api('publish',{revision:state.revision});state={...state,...result};stamp();message('Published. Your website now shows these changes.');}catch(error){message(error.message);}finally{lock(false);}};
document.querySelector('#reset').onclick=async()=>{if(!await confirmAction('Discard draft changes?','This restores the draft to the currently published website. Your live website stays the same.'))return;lock(true);try{const result=await api('reset',{revision:state.revision});state={...state,...result};content=structuredClone(state.draft);dirty=false;drawText();drawPhotos();message('Draft restored to published content.');}catch(error){message(error.message);}finally{lock(false);}};
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));for(const id of ['text','photos'])document.getElementById(id).hidden=id!==button.dataset.tab;});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
async function load(){try{state=await api('state');content=structuredClone(state.draft);drawText();drawPhotos();stamp();lock(false);message('Ready. Your draft is saved separately from your website.');}catch(error){message(error.message+' Reload this page to try again.');}}
load();
